FROM python
RUN pip install flask
RUN pip install requests
COPY  ./static /home/BRA9.1_Team65/static/
COPY  ./templates /home/BRA9.1_Team65/templates/
COPY  main.py /home/BRA9.1_Team65/
EXPOSE 5000
CMD python3 /home/BRA9.1_Team65/main.py
FROM python
RUN pip install flask
RUN pip install requests
COPY  ./static /home/BRA9.1_Team65/static/
COPY  ./templates /home/BRA9.1_Team65/templates/
COPY  main.py /home/BRA9.1_Team65/
EXPOSE 5000
CMD python3 /home/BRA9.1_Team65/main.py
